#登陆相关配置
login:
  #开放的模拟登陆api服务器地址
  api: "http://www.zimo.wiki:8080/wisedu-unified-login-api-v1.0/api/login"
#用户组配置
users:
  #单个用户配置
  - user:
      #username 学号或者工号
      username: '161105024'
      #password 密码
      password: '161105024'
      #address 地址，定位信息
      address: 中国四川省成都市金牛区一环路北1段-129号-附9号
      #email 接受通知消息的邮箱
      email: 461009747@qq.com
      #school 学校全称
      school: 云南财经大学
  #多用户配置，将下面的注释去掉即可，如果有表单内容有图片，不建议使用多用户配置
#  - user:
#      #username 学号或者工号
#      username: 161105024
#      #password 密码
#      password: 161105024
#      #address 地址
#      address: 中国四川省成都市金牛区一环路北1段-129号-附9号
#      #email 接受通知消息的邮箱
#      email: 461009747@qq.com
#      school: 宜宾学院
#今日校园相关配置
cpdaily:
  #表单组默认选项配置
  defaults:
    #表单默认选项配置，按顺序，注意，只有标必填项的才处理
    - default:
        title: 你目前是否有发热、干咳、气促等呼吸道症状 ？
        type: 2
        value: 否
    - default:
        title: 过去14天是否接触过确诊病例、疑似病例、无症状感染者？
        type: 2
        value: 否
    - default:
        title: 过去14天是否有高风险、中风险地区旅居史或境外其他国家和地区旅居史？
        type: 2
        value: 否
    - default:
        title: 你今天的腋下体温是多少？
        type: 2
        value: A.体温正常37.3℃以下
    - default:
        title: 本人是否承诺以上所填报的全部内容均属实、准确？
        type: 2
        value: 是
